name: main

on: [push]

jobs:
  appimage_aarch64:
    runs-on: ARM64
    container: arm64v8/ubuntu:18.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build AppImage with build_appimage.sh
        run: ./build_appimage.sh
        env:
          CARCH: 'aarch64'
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v3
        with:
          path: "LibreWolf-*-*.*.AppImage*"
